In [126]:
import numpy as np
import pandas as pd

In [92]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [93]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [94]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

# working with dates dataset first

In [95]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [96]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [97]:
date.isnull().sum()

date          0
product_id    0
city_id       0
orders        0
dtype: int64

In [98]:
# we can  see that there is date in str we will first convert into the interger

In [99]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [100]:
date['date']

0     2019-12-10
1     2018-08-15
2     2018-10-23
3     2019-08-17
4     2019-01-06
         ...
995   2018-10-08
996   2018-12-06
997   2019-05-07
998   2019-03-03
999   2019-10-15
Name: date, Length: 1000, dtype: datetime64[ns]

In [101]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [102]:
# 1. extracting the year first

In [103]:
date['date_year'] = date['date'].dt.year

In [104]:
date.head(10)

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019
5 2018-08-23        1811       25       4       2018
6 2018-11-21        1282       26       1       2018
7 2019-03-27        5022        2      41       2019
8 2019-06-29        3699        3      15       2019
9 2018-08-30        4373       11       3       2018

In [105]:
# 2. extracting the month now

In [106]:
date['date_month_no'] = date['date'].dt.month

In [107]:
date

          date  product_id  city_id  orders  date_year  date_month_no
0   2019-12-10        5628       25       3       2019             12
1   2018-08-15        3646       14     157       2018              8
2   2018-10-23        1859       25       1       2018             10
3   2019-08-17        7292       25       1       2019              8
4   2019-01-06        4344       25       3       2019              1
..         ...         ...      ...     ...        ...            ...
995 2018-10-08         255       13       1       2018             10
996 2018-12-06        5521        7       1       2018             12
997 2019-05-07         487       26      14       2019              5
998 2019-03-03        1503       21       2       2019              3
999 2019-10-15        6371        7      22       2019             10

[1000 rows x 6 columns]

In [108]:
# 3. month name now

In [109]:
date['date_month_name'] = date['date'].dt.month_name()

In [110]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [111]:
# day now

In [112]:
date['date_day'] = date['date'].dt.day

In [116]:
date.sample(20)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
942,2019-11-16,2999,7,1,2019,11,November,5
669,2018-10-31,1647,4,1,2018,10,October,2
826,2018-09-22,944,28,1,2018,9,September,5
314,2018-10-06,4845,22,4,2018,10,October,5
290,2018-12-05,4254,16,37,2018,12,December,2
47,2018-12-11,3437,14,2,2018,12,December,1
146,2019-12-13,6828,13,1,2019,12,December,4
871,2018-12-26,7378,21,8,2018,12,December,2
597,2018-10-18,4846,1,1,2018,10,October,3
714,2019-08-07,4659,1,1,2019,8,August,2
981,2019-06-17,7526,14,12,2019,6,June,0
153,2019-01-13,4576,22,1,2019,1,January,6
67,2018-11-18,3604,16,5,2018,11,November,6
208,2019-06-24,3919,2,22,2019,6,June,0
650,2019-05-21,5626,22,1,2019,5,May,1
317,2018-08-31,3088,14,106,2018,8,August,4
983,2019-08-02,6399,0,1,2019,8,August,4
239,2019-02-19,4823,18,26,2019,2,February,1
838,2019-11-23,4191,16,1,2019,11,November,5
287,2018-12-15,6368,25,1,2018,12,December,5

In [117]:
# week now

In [118]:
date['date_day'] = date['date'].dt.dayofweek

In [119]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,1
1,2018-08-15,3646,14,157,2018,8,August,2
2,2018-10-23,1859,25,1,2018,10,October,1
3,2019-08-17,7292,25,1,2019,8,August,5
4,2019-01-06,4344,25,3,2019,1,January,6

In [120]:
# day of week - name

In [121]:
date['date_day_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_month_name  date_day date_day_name
0 2019-12-10       2019             12        December         1       Tuesday
1 2018-08-15       2018              8          August         2     Wednesday
2 2018-10-23       2018             10         October         1       Tuesday
3 2019-08-17       2019              8          August         5      Saturday
4 2019-01-06       2019              1         January         6        Sunday

In [122]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [124]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [125]:
# is weekend or not 

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

KeyError: 'date_dow_name'

In [64]:
# extrct year week

In [63]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_day_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,1,1,Tuesday,Tuesday,0,50
1,2018-08-15,2018,8,August,2,2,Wednesday,Wednesday,0,33
2,2018-10-23,2018,10,October,1,1,Tuesday,Tuesday,0,43
3,2019-08-17,2019,8,August,5,5,Saturday,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,Sunday,1,1

In [65]:
# quartile

In [66]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_day_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,1,1,Tuesday,Tuesday,0,50,4
1,2018-08-15,2018,8,August,2,2,Wednesday,Wednesday,0,33,3
2,2018-10-23,2018,10,October,1,1,Tuesday,Tuesday,0,43,4
3,2019-08-17,2019,8,August,5,5,Saturday,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,Sunday,1,1,1

In [67]:
# Extract Semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_day_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,1,1,Tuesday,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,2,2,Wednesday,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,1,1,Tuesday,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,5,5,Saturday,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,Sunday,1,1,1,1

# extrct time

In [127]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 19, 12, 23, 47, 317940)

In [69]:
today - date['date']

0     2291 days 12:16:10.655122
1     2773 days 12:16:10.655122
2     2704 days 12:16:10.655122
3     2406 days 12:16:10.655122
4     2629 days 12:16:10.655122
                 ...
995   2719 days 12:16:10.655122
996   2660 days 12:16:10.655122
997   2508 days 12:16:10.655122
998   2573 days 12:16:10.655122
999   2347 days 12:16:10.655122
Name: date, Length: 1000, dtype: timedelta64[ns]

In [70]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [71]:
time.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [73]:
time.isnull().sum()

date    0
msg     0
dtype: int64

In [74]:
(today - date['date']).dt.days

0      2291
1      2773
2      2704
3      2406
4      2629
       ...
995    2719
996    2660
997    2508
998    2573
999    2347
Name: date, Length: 1000, dtype: int64

In [83]:
# Months passed

date['months_diff'] = ((today - date['date']).dt.days // 30)

In [84]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
 2   hour    1000 non-null   int32
 3   min     1000 non-null   int32
 4   sec     1000 non-null   int32
 5   time    1000 non-null   object
dtypes: datetime64[ns](1), int32(3), object(2)
memory usage: 35.3+ KB

In [85]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [86]:
# Extract Time part


time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [87]:
# Time difference
today - time['date']

0     4477 days 11:26:10.655122
1     4341 days 12:36:10.655122
2     4827 days 11:55:10.655122
3     4129 days 11:45:10.655122
4     4526 days 13:05:10.655122
                 ...
995   5116 days 11:26:10.655122
996   4437 days 13:02:10.655122
997   4902 days 12:39:10.655122
998   5018 days 12:42:10.655122
999   4290 days 12:51:10.655122
Name: date, Length: 1000, dtype: timedelta64[ns]

In [88]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.868540e+08
1      3.751078e+08
2      4.170957e+08
3      3.567879e+08
4      3.910935e+08
           ...
995    4.420636e+08
996    3.834037e+08
997    4.235784e+08
998    4.336009e+08
999    3.707023e+08
Name: date, Length: 1000, dtype: float64

In [89]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.447566e+06
1      6.251796e+06
2      6.951595e+06
3      5.946465e+06
4      6.518225e+06
           ...
995    7.367726e+06
996    6.390062e+06
997    7.059639e+06
998    7.226682e+06
999    6.178371e+06
Name: date, Length: 1000, dtype: float64

In [90]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107459.436293
1      104196.602960
2      115859.919626
3       99107.752960
4      108637.086293
           ...
995    122795.436293
996    106501.036293
997    117660.652960
998    120444.702960
999    102972.852960
Name: date, Length: 1000, dtype: float64