In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.sample(5)

      Age  Pclass  SibSp  Parch  Survived
114  17.0       3      0      0         0
412  33.0       1      1      0         1
807  18.0       3      0      0         0
177  50.0       1      0      0         0
185   NaN       1      0      0         0

# Feature Construction

In [4]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [11]:
df.dropna(inplace = True)
# missing data in age is dopped

In [12]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [13]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [14]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [19]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=50))

np.float64(0.698952380952381)

In [20]:
# feature construction ---->>

In [21]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1
# yaha 1 woh memeber add hota ha woh bhe family ka part hai

In [26]:
X.head(20)

     Age  Pclass  SibSp  Parch  Family_size
0   22.0       3      1      0            2
1   38.0       1      1      0            2
2   26.0       3      0      0            1
3   35.0       1      1      0            2
4   35.0       3      0      0            1
6   54.0       1      0      0            1
7    2.0       3      3      1            5
8   27.0       3      0      2            3
9   14.0       2      1      0            2
10   4.0       3      1      1            3
11  58.0       1      0      0            1
12  20.0       3      0      0            1
13  39.0       3      1      5            7
14  14.0       3      0      0            1
15  55.0       2      0      0            1
16   2.0       3      4      1            6
18  31.0       3      1      0            2
20  35.0       2      0      0            1
21  34.0       2      0      0            1
22  15.0       3      0      0            1

In [38]:
def myfunc(num):
    if num == 1:
        #alone aik bnda
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    elif num >= 4:
        return 2
        # large family
    else:
        print('Enter Valid Number, Please!')

In [39]:
myfunc(3)

1

In [40]:
myfunc(4)

1

In [41]:
myfunc(9)

2

In [42]:
myfunc(0)

Enter Valid Number, Please!

In [43]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [44]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [45]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [46]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [48]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=50))

np.float64(0.7019047619047619)

# Feature Splitting

In [49]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [51]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [52]:
# we can in names there is first name then  , Then Mr. or something else then last name 
# we will spilt names and we will check using surname survival chance

In [65]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [66]:
# in this case when we apply split() then there is two thing we git  [0] mean befor , 
# and [1] means after the ,

In [67]:
df['Name'].str.split(', ', expand=True)[1]

0                                 Mr. Owen Harris
1      Mrs. John Bradley (Florence Briggs Thayer)
2                                     Miss. Laina
3              Mrs. Jacques Heath (Lily May Peel)
4                               Mr. William Henry
                          ...
886                                   Rev. Juozas
887                          Miss. Margaret Edith
888                Miss. Catherine Helen "Carrie"
889                               Mr. Karl Howell
890                                   Mr. Patrick
Name: 1, Length: 891, dtype: object

In [68]:
df['Name'].str.split(', ', expand=True)[0]

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: 0, Length: 891, dtype: object

In [69]:
# then we applied split for dot

In [70]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)

        0                                       1     2
0      Mr                             Owen Harris  None
1     Mrs   John Bradley (Florence Briggs Thayer)  None
2    Miss                                   Laina  None
3     Mrs           Jacques Heath (Lily May Peel)  None
4      Mr                           William Henry  None
..    ...                                     ...   ...
886   Rev                                  Juozas  None
887  Miss                          Margaret Edith  None
888  Miss                Catherine Helen "Carrie"  None
889    Mr                             Karl Howell  None
890    Mr                                 Patrick  None

[891 rows x 3 columns]

In [74]:
df['Title']

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: Title, Length: 891, dtype: object

In [78]:
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [80]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)
# here we can check the survival rate 
# as there was most of the name contain mr and miss or mrs so that is why thier survival rate is high 
# other memebr show 1.0 thats were too small passergenr with this names so that is why the have high rate of survival

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [81]:
# so that's end

In [83]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1
# this is just for how to make col

C:\Users\engrf\AppData\Local\Temp\ipykernel_14980\3556943245.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1
C:\Users\engrf\AppData\Local\Temp\ipykernel_14980\3556943245.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [86]:
df['Is_Married'].value_counts()

Is_Married
0    766
1    125
Name: count, dtype: int64